spring.application.name=Backend
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/Backend_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Kaveri@2005}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:mySecretKeyForResourceBookingSystem123456789}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}